# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9860d0d22d7cbf3f17c5854697777538dbf77a09967929845144559185ce05734ee48782f6007298376a9be135f083f3ebf130e01959fd0b35a5cfa2dc2f3f

test:
  secret_key_base: d69bcd395343662fb221ec74a86dcec55d24374c8cf5e1ee1648f6ab49c3240ff187fb5059b83c0007f994370bfa48400eeb072c571709f3588b8b5f55c7a106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
